# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linear_solver <- function(A, B) {
    .Call(`_RcppWass_linear_solver`, A, B)
}

quadprog <- function(A, b, C, d, lb, ub) {
    .Call(`_RcppWass_quadprog`, A, b, C, d, lb, ub)
}

wasser <- function(xfit, q, Q0, xpred, t, qdmin) {
    .Call(`_RcppWass_wasser`, xfit, q, Q0, xpred, t, qdmin)
}

confidence_band <- function(xfit, xpred, Q_obs, q_obs, t_vec, alpha) {
    .Call(`_RcppWass_confidence_band`, xfit, xpred, Q_obs, q_obs, t_vec, alpha)
}

nadayara_pred <- function(distancias, X, t, Y, hs) {
    .Call(`_RcppWass_nadayara_pred`, distancias, X, t, Y, hs)
}

nadayara_reg <- function(X, t, Y, hs, indices_1, indices_2) {
    .Call(`_RcppWass_nadayara_reg`, X, t, Y, hs, indices_1, indices_2)
}

eucdistance1 <- function(X, t) {
    .Call(`_RcppWass_eucdistance1`, X, t)
}

