# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linear_solver <- function(A, B) {
    .Call(`_RcppWass_linear_solver`, A, B)
}

quadprog <- function(A, b, C, d, lb, ub) {
    .Call(`_RcppWass_quadprog`, A, b, C, d, lb, ub)
}

wasser <- function(xfit, q, Q0, xpred, t, qdmin) {
    .Call(`_RcppWass_wasser`, xfit, q, Q0, xpred, t, qdmin)
}

confidence_band <- function(xfit, xpred, Q_obs, q_obs, t_vec, alpha) {
    .Call(`_RcppWass_confidence_band`, xfit, xpred, Q_obs, q_obs, t_vec, alpha)
}

